// <auto-generated />
using System;
using InterviewPrepApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewPrepApp.Infrastructure.Migrations.SeedCategories
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316022934_SeedCategories")]
    partial class SeedCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fundamentals"
                        },
                        new
                        {
                            Id = 2,
                            Name = "OOPS",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Abstraction",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Abstract Classes",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Interfaces",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Encapsulation",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Inheritance",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Polymorphism",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "SOLID",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Single Responsibility",
                            ParentId = 9
                        },
                        new
                        {
                            Id = 11,
                            Name = "Open-Closed",
                            ParentId = 9
                        },
                        new
                        {
                            Id = 12,
                            Name = "Liskov Substitution",
                            ParentId = 9
                        },
                        new
                        {
                            Id = 13,
                            Name = "Interface Segregation",
                            ParentId = 9
                        },
                        new
                        {
                            Id = 14,
                            Name = "Dependency Inversion",
                            ParentId = 9
                        },
                        new
                        {
                            Id = 15,
                            Name = "Backend"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Middleware",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 17,
                            Name = "Request Pipeline",
                            ParentId = 16
                        },
                        new
                        {
                            Id = 18,
                            Name = "Error Handling",
                            ParentId = 16
                        },
                        new
                        {
                            Id = 19,
                            Name = "Logging",
                            ParentId = 16
                        },
                        new
                        {
                            Id = 20,
                            Name = "Caching",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 21,
                            Name = "HTTP Caching",
                            ParentId = 20
                        },
                        new
                        {
                            Id = 22,
                            Name = "Cache Headers",
                            ParentId = 20
                        },
                        new
                        {
                            Id = 23,
                            Name = "Cache-Control",
                            ParentId = 22
                        },
                        new
                        {
                            Id = 24,
                            Name = "Expires",
                            ParentId = 22
                        },
                        new
                        {
                            Id = 25,
                            Name = "ETag",
                            ParentId = 22
                        },
                        new
                        {
                            Id = 26,
                            Name = "CDN",
                            ParentId = 20
                        },
                        new
                        {
                            Id = 27,
                            Name = "API Design",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 28,
                            Name = "REST",
                            ParentId = 27
                        },
                        new
                        {
                            Id = 29,
                            Name = "HTTP Methods",
                            ParentId = 28
                        },
                        new
                        {
                            Id = 30,
                            Name = "Status Codes",
                            ParentId = 28
                        },
                        new
                        {
                            Id = 31,
                            Name = "Resource Design",
                            ParentId = 28
                        },
                        new
                        {
                            Id = 32,
                            Name = "GraphQL",
                            ParentId = 27
                        },
                        new
                        {
                            Id = 33,
                            Name = "Queries",
                            ParentId = 32
                        },
                        new
                        {
                            Id = 34,
                            Name = "Mutations",
                            ParentId = 32
                        },
                        new
                        {
                            Id = 35,
                            Name = "Subscriptions",
                            ParentId = 32
                        },
                        new
                        {
                            Id = 36,
                            Name = "gRPC",
                            ParentId = 27
                        },
                        new
                        {
                            Id = 37,
                            Name = "Database",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 38,
                            Name = "SQL",
                            ParentId = 37
                        },
                        new
                        {
                            Id = 39,
                            Name = "Indexes",
                            ParentId = 38
                        },
                        new
                        {
                            Id = 40,
                            Name = "Transactions",
                            ParentId = 38
                        },
                        new
                        {
                            Id = 41,
                            Name = "Joins",
                            ParentId = 38
                        },
                        new
                        {
                            Id = 42,
                            Name = "NoSQL",
                            ParentId = 37
                        },
                        new
                        {
                            Id = 43,
                            Name = "Document DB",
                            ParentId = 42
                        },
                        new
                        {
                            Id = 44,
                            Name = "Key-Value",
                            ParentId = 42
                        },
                        new
                        {
                            Id = 45,
                            Name = "Graph DB",
                            ParentId = 42
                        },
                        new
                        {
                            Id = 46,
                            Name = "ORM",
                            ParentId = 37
                        },
                        new
                        {
                            Id = 47,
                            Name = "Entity Framework",
                            ParentId = 46
                        },
                        new
                        {
                            Id = 48,
                            Name = "Dapper",
                            ParentId = 46
                        },
                        new
                        {
                            Id = 49,
                            Name = "NHibernate",
                            ParentId = 46
                        },
                        new
                        {
                            Id = 50,
                            Name = "Security",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 51,
                            Name = "Authentication",
                            ParentId = 50
                        },
                        new
                        {
                            Id = 52,
                            Name = "JWT",
                            ParentId = 51
                        },
                        new
                        {
                            Id = 53,
                            Name = "OAuth",
                            ParentId = 51
                        },
                        new
                        {
                            Id = 54,
                            Name = "Basic Auth",
                            ParentId = 51
                        },
                        new
                        {
                            Id = 55,
                            Name = "Authorization",
                            ParentId = 50
                        },
                        new
                        {
                            Id = 56,
                            Name = "Roles",
                            ParentId = 55
                        },
                        new
                        {
                            Id = 57,
                            Name = "Policies",
                            ParentId = 55
                        },
                        new
                        {
                            Id = 58,
                            Name = "Claims",
                            ParentId = 55
                        },
                        new
                        {
                            Id = 59,
                            Name = "Encryption",
                            ParentId = 50
                        },
                        new
                        {
                            Id = 60,
                            Name = "CORS",
                            ParentId = 50
                        },
                        new
                        {
                            Id = 61,
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 62,
                            Name = "ASP.NET Core",
                            ParentId = 61
                        },
                        new
                        {
                            Id = 63,
                            Name = "Entity Framework Core",
                            ParentId = 61
                        },
                        new
                        {
                            Id = 64,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Components",
                            ParentId = 64
                        },
                        new
                        {
                            Id = 66,
                            Name = "RxJS",
                            ParentId = 64
                        },
                        new
                        {
                            Id = 67,
                            Name = "System Design"
                        },
                        new
                        {
                            Id = 68,
                            Name = "High-Level Design",
                            ParentId = 67
                        },
                        new
                        {
                            Id = 69,
                            Name = "Low-Level Design",
                            ParentId = 67
                        },
                        new
                        {
                            Id = 70,
                            Name = "Scalability",
                            ParentId = 67
                        });
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.UserProgress", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRevision")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSolved")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Category", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Question", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.UserProgress", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Question", "Question")
                        .WithMany("UserProgresses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Category", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Question", b =>
                {
                    b.Navigation("UserProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
