// <auto-generated />
using System;
using InterviewPrepApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewPrepApp.Infrastructure.Migrations.SeedCategories
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260320161806_AddAdminTables")]
    partial class AddAdminTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fundamentals",
                            Slug = "fundamentals"
                        },
                        new
                        {
                            Id = 2,
                            Name = "OOPS",
                            ParentId = 1,
                            Slug = "oops"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Abstraction",
                            ParentId = 2,
                            Slug = "abstraction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Abstract Classes",
                            ParentId = 3,
                            Slug = "abstract-classes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Interfaces",
                            ParentId = 3,
                            Slug = "interfaces"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Encapsulation",
                            ParentId = 2,
                            Slug = "encapsulation"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Inheritance",
                            ParentId = 2,
                            Slug = "inheritance"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Polymorphism",
                            ParentId = 2,
                            Slug = "polymorphism"
                        },
                        new
                        {
                            Id = 9,
                            Name = "SOLID",
                            ParentId = 1,
                            Slug = "solid"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Single Responsibility",
                            ParentId = 9,
                            Slug = "srp"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Open-Closed",
                            ParentId = 9,
                            Slug = "ocp"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Liskov Substitution",
                            ParentId = 9,
                            Slug = "lsp"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Interface Segregation",
                            ParentId = 9,
                            Slug = "isp"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Dependency Inversion",
                            ParentId = 9,
                            Slug = "dip"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Backend",
                            Slug = "backend"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Middleware",
                            ParentId = 15,
                            Slug = "middleware"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Request Pipeline",
                            ParentId = 16,
                            Slug = "request-pipeline"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Error Handling",
                            ParentId = 16,
                            Slug = "error-handling"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Logging",
                            ParentId = 16,
                            Slug = "logging"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Caching",
                            ParentId = 15,
                            Slug = "caching"
                        },
                        new
                        {
                            Id = 21,
                            Name = "HTTP Caching",
                            ParentId = 20,
                            Slug = "http-caching"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Cache Headers",
                            ParentId = 20,
                            Slug = "cache-headers"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Cache-Control",
                            ParentId = 22,
                            Slug = "cache-control"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Expires",
                            ParentId = 22,
                            Slug = "expires"
                        },
                        new
                        {
                            Id = 25,
                            Name = "ETag",
                            ParentId = 22,
                            Slug = "etag"
                        },
                        new
                        {
                            Id = 26,
                            Name = "CDN",
                            ParentId = 20,
                            Slug = "cdn"
                        },
                        new
                        {
                            Id = 27,
                            Name = "API Design",
                            ParentId = 15,
                            Slug = "api-design"
                        },
                        new
                        {
                            Id = 28,
                            Name = "REST",
                            ParentId = 27,
                            Slug = "rest"
                        },
                        new
                        {
                            Id = 29,
                            Name = "HTTP Methods",
                            ParentId = 28,
                            Slug = "http-methods"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Status Codes",
                            ParentId = 28,
                            Slug = "status-codes"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Resource Design",
                            ParentId = 28,
                            Slug = "resource-design"
                        },
                        new
                        {
                            Id = 32,
                            Name = "GraphQL",
                            ParentId = 27,
                            Slug = "graphql"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Queries",
                            ParentId = 32,
                            Slug = "queries"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Mutations",
                            ParentId = 32,
                            Slug = "mutations"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Subscriptions",
                            ParentId = 32,
                            Slug = "subscriptions"
                        },
                        new
                        {
                            Id = 36,
                            Name = "gRPC",
                            ParentId = 27,
                            Slug = "grpc"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Database",
                            ParentId = 15,
                            Slug = "database"
                        },
                        new
                        {
                            Id = 38,
                            Name = "SQL",
                            ParentId = 37,
                            Slug = "sql"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Indexes",
                            ParentId = 38,
                            Slug = "indexes"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Transactions",
                            ParentId = 38,
                            Slug = "transactions"
                        },
                        new
                        {
                            Id = 41,
                            Name = "NoSQL",
                            ParentId = 37,
                            Slug = "nosql"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Document DB",
                            ParentId = 41,
                            Slug = "document-db"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Key-Value",
                            ParentId = 41,
                            Slug = "key-value"
                        },
                        new
                        {
                            Id = 44,
                            Name = "ORM",
                            ParentId = 37,
                            Slug = "orm"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Entity Framework",
                            ParentId = 44,
                            Slug = "entity-framework"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Dapper",
                            ParentId = 44,
                            Slug = "dapper"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Security",
                            ParentId = 15,
                            Slug = "security"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Authentication",
                            ParentId = 47,
                            Slug = "authentication"
                        },
                        new
                        {
                            Id = 49,
                            Name = "JWT",
                            ParentId = 48,
                            Slug = "jwt"
                        },
                        new
                        {
                            Id = 50,
                            Name = "OAuth",
                            ParentId = 48,
                            Slug = "oauth"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Basic Auth",
                            ParentId = 48,
                            Slug = "basic-auth"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Authorization",
                            ParentId = 47,
                            Slug = "authorization"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Roles",
                            ParentId = 52,
                            Slug = "roles"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Policies",
                            ParentId = 52,
                            Slug = "policies"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Claims",
                            ParentId = 52,
                            Slug = "claims"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Encryption",
                            ParentId = 47,
                            Slug = "encryption"
                        },
                        new
                        {
                            Id = 57,
                            Name = "CORS",
                            ParentId = 47,
                            Slug = "cors"
                        },
                        new
                        {
                            Id = 58,
                            Name = ".NET",
                            Slug = "dotnet"
                        },
                        new
                        {
                            Id = 59,
                            Name = "ASP.NET Core",
                            ParentId = 58,
                            Slug = "aspnet-core"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Entity Framework Core",
                            ParentId = 58,
                            Slug = "ef-core"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Angular",
                            Slug = "angular"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Components",
                            ParentId = 61,
                            Slug = "components"
                        },
                        new
                        {
                            Id = 63,
                            Name = "RxJS",
                            ParentId = 61,
                            Slug = "rxjs"
                        },
                        new
                        {
                            Id = 64,
                            Name = "System Design",
                            Slug = "system-design"
                        },
                        new
                        {
                            Id = 65,
                            Name = "High-Level Design",
                            ParentId = 64,
                            Slug = "hld"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Low-Level Design",
                            ParentId = 64,
                            Slug = "lld"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Scalability",
                            ParentId = 64,
                            Slug = "scalability"
                        });
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuestionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("QuestionVersions");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.UserProgress", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRevision")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSolved")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Category", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Question", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuestionVersion", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Question", "Question")
                        .WithMany("Versions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.UserProgress", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Question", "Question")
                        .WithMany("UserProgresses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Category", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Question", b =>
                {
                    b.Navigation("UserProgresses");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
