// <auto-generated />
using System;
using InterviewPrepApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewPrepApp.Infrastructure.Migrations.SeedCategories
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260426202425_SeedDashboard")]
    partial class SeedDashboard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fundamentals",
                            Slug = "fundamentals"
                        },
                        new
                        {
                            Id = 2,
                            Name = "OOPS",
                            ParentId = 1,
                            Slug = "oops"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Abstraction",
                            ParentId = 2,
                            Slug = "abstraction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Abstract Classes",
                            ParentId = 3,
                            Slug = "abstract-classes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Interfaces",
                            ParentId = 3,
                            Slug = "interfaces"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Encapsulation",
                            ParentId = 2,
                            Slug = "encapsulation"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Inheritance",
                            ParentId = 2,
                            Slug = "inheritance"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Polymorphism",
                            ParentId = 2,
                            Slug = "polymorphism"
                        },
                        new
                        {
                            Id = 9,
                            Name = "SOLID",
                            ParentId = 1,
                            Slug = "solid"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Single Responsibility",
                            ParentId = 9,
                            Slug = "srp"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Open-Closed",
                            ParentId = 9,
                            Slug = "ocp"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Liskov Substitution",
                            ParentId = 9,
                            Slug = "lsp"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Interface Segregation",
                            ParentId = 9,
                            Slug = "isp"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Dependency Inversion",
                            ParentId = 9,
                            Slug = "dip"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Backend",
                            Slug = "backend"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Middleware",
                            ParentId = 15,
                            Slug = "middleware"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Request Pipeline",
                            ParentId = 16,
                            Slug = "request-pipeline"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Error Handling",
                            ParentId = 16,
                            Slug = "error-handling"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Logging",
                            ParentId = 16,
                            Slug = "logging"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Caching",
                            ParentId = 15,
                            Slug = "caching"
                        },
                        new
                        {
                            Id = 21,
                            Name = "HTTP Caching",
                            ParentId = 20,
                            Slug = "http-caching"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Cache Headers",
                            ParentId = 20,
                            Slug = "cache-headers"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Cache-Control",
                            ParentId = 22,
                            Slug = "cache-control"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Expires",
                            ParentId = 22,
                            Slug = "expires"
                        },
                        new
                        {
                            Id = 25,
                            Name = "ETag",
                            ParentId = 22,
                            Slug = "etag"
                        },
                        new
                        {
                            Id = 26,
                            Name = "CDN",
                            ParentId = 20,
                            Slug = "cdn"
                        },
                        new
                        {
                            Id = 27,
                            Name = "API Design",
                            ParentId = 15,
                            Slug = "api-design"
                        },
                        new
                        {
                            Id = 28,
                            Name = "REST",
                            ParentId = 27,
                            Slug = "rest"
                        },
                        new
                        {
                            Id = 29,
                            Name = "HTTP Methods",
                            ParentId = 28,
                            Slug = "http-methods"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Status Codes",
                            ParentId = 28,
                            Slug = "status-codes"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Resource Design",
                            ParentId = 28,
                            Slug = "resource-design"
                        },
                        new
                        {
                            Id = 32,
                            Name = "GraphQL",
                            ParentId = 27,
                            Slug = "graphql"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Queries",
                            ParentId = 32,
                            Slug = "queries"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Mutations",
                            ParentId = 32,
                            Slug = "mutations"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Subscriptions",
                            ParentId = 32,
                            Slug = "subscriptions"
                        },
                        new
                        {
                            Id = 36,
                            Name = "gRPC",
                            ParentId = 27,
                            Slug = "grpc"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Database",
                            ParentId = 15,
                            Slug = "database"
                        },
                        new
                        {
                            Id = 38,
                            Name = "SQL",
                            ParentId = 37,
                            Slug = "sql"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Indexes",
                            ParentId = 38,
                            Slug = "indexes"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Transactions",
                            ParentId = 38,
                            Slug = "transactions"
                        },
                        new
                        {
                            Id = 41,
                            Name = "NoSQL",
                            ParentId = 37,
                            Slug = "nosql"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Document DB",
                            ParentId = 41,
                            Slug = "document-db"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Key-Value",
                            ParentId = 41,
                            Slug = "key-value"
                        },
                        new
                        {
                            Id = 44,
                            Name = "ORM",
                            ParentId = 37,
                            Slug = "orm"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Entity Framework",
                            ParentId = 44,
                            Slug = "entity-framework"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Dapper",
                            ParentId = 44,
                            Slug = "dapper"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Security",
                            ParentId = 15,
                            Slug = "security"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Authentication",
                            ParentId = 47,
                            Slug = "authentication"
                        },
                        new
                        {
                            Id = 49,
                            Name = "JWT",
                            ParentId = 48,
                            Slug = "jwt"
                        },
                        new
                        {
                            Id = 50,
                            Name = "OAuth",
                            ParentId = 48,
                            Slug = "oauth"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Basic Auth",
                            ParentId = 48,
                            Slug = "basic-auth"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Authorization",
                            ParentId = 47,
                            Slug = "authorization"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Roles",
                            ParentId = 52,
                            Slug = "roles"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Policies",
                            ParentId = 52,
                            Slug = "policies"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Claims",
                            ParentId = 52,
                            Slug = "claims"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Encryption",
                            ParentId = 47,
                            Slug = "encryption"
                        },
                        new
                        {
                            Id = 57,
                            Name = "CORS",
                            ParentId = 47,
                            Slug = "cors"
                        },
                        new
                        {
                            Id = 58,
                            Name = ".NET",
                            Slug = "dotnet"
                        },
                        new
                        {
                            Id = 59,
                            Name = "ASP.NET Core",
                            ParentId = 58,
                            Slug = "aspnet-core"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Entity Framework Core",
                            ParentId = 58,
                            Slug = "ef-core"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Angular",
                            Slug = "angular"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Components",
                            ParentId = 61,
                            Slug = "components"
                        },
                        new
                        {
                            Id = 63,
                            Name = "RxJS",
                            ParentId = 61,
                            Slug = "rxjs"
                        },
                        new
                        {
                            Id = 64,
                            Name = "System Design",
                            Slug = "system-design"
                        },
                        new
                        {
                            Id = 65,
                            Name = "High-Level Design",
                            ParentId = 64,
                            Slug = "hld"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Low-Level Design",
                            ParentId = 64,
                            Slug = "lld"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Scalability",
                            ParentId = 64,
                            Slug = "scalability"
                        });
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.CheatSheetResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MarkdownContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryId", "Type");

                    b.ToTable("CheatSheetResources");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.DevHexagon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("DevHexagons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role = ".NET Full Stack Engineer",
                            TargetLevel = "Intermediate/Senior",
                            Version = "2026.2"
                        });
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorSummaryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedRows")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("LastProcessedBatch")
                        .HasColumnType("int");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("int");

                    b.Property<string>("RetryPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TempFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UploadedByUserId", "UploadedAtUtc");

                    b.ToTable("ImportJobs");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.PrimaryMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DevHexagonId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DevHexagonId");

                    b.ToTable("PrimaryMetrics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DevHexagonId = 1,
                            Value = "Sub-50ms latency"
                        },
                        new
                        {
                            Id = 2,
                            DevHexagonId = 1,
                            Value = "500+ concurrent users"
                        });
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuestionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("QuestionVersions");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuizAttemptQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswerSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExplanationSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionASnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionBSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionCSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionDSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("QuestionTextSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizAttemptId")
                        .HasColumnType("int");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizAttemptId");

                    b.HasIndex("QuizQuestionId");

                    b.ToTable("QuizAttemptQuestions");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuizAttemptResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnsweredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuizAttemptQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuizAttemptQuestionId")
                        .IsUnique();

                    b.ToTable("QuizAttemptResponses");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SkillCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SkillCategoryId");

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SkillCategoryId = 1,
                            TopicName = "Concurrency (async/await, Task, Thread Pool)"
                        },
                        new
                        {
                            Id = 2,
                            SkillCategoryId = 1,
                            TopicName = "Garbage Collection (Gen 0/1/2, LOH, IDisposable)"
                        },
                        new
                        {
                            Id = 3,
                            SkillCategoryId = 1,
                            TopicName = "Dependency Injection (Lifetimes, Scopes)"
                        },
                        new
                        {
                            Id = 4,
                            SkillCategoryId = 1,
                            TopicName = "Middleware & Request Pipeline"
                        },
                        new
                        {
                            Id = 5,
                            SkillCategoryId = 1,
                            TopicName = "Minimal APIs vs. Controllers"
                        },
                        new
                        {
                            Id = 6,
                            SkillCategoryId = 1,
                            TopicName = "Performance Profiling (BenchmarkDotNet, dotTrace)"
                        },
                        new
                        {
                            Id = 7,
                            SkillCategoryId = 1,
                            TopicName = "Caching Strategies (MemoryCache, Distributed Cache)"
                        },
                        new
                        {
                            Id = 8,
                            SkillCategoryId = 1,
                            TopicName = "Background Services (IHostedService)"
                        },
                        new
                        {
                            Id = 9,
                            SkillCategoryId = 1,
                            TopicName = "Exception Handling & Resiliency (Polly)"
                        },
                        new
                        {
                            Id = 10,
                            SkillCategoryId = 1,
                            TopicName = "Clean Architecture"
                        },
                        new
                        {
                            Id = 11,
                            SkillCategoryId = 2,
                            TopicName = "RxJS & Reactive Programming (Observables, Subjects)"
                        },
                        new
                        {
                            Id = 12,
                            SkillCategoryId = 2,
                            TopicName = "Signal-Based State Management"
                        },
                        new
                        {
                            Id = 13,
                            SkillCategoryId = 2,
                            TopicName = "Component Lifecycle & Change Detection (OnPush)"
                        },
                        new
                        {
                            Id = 14,
                            SkillCategoryId = 2,
                            TopicName = "Lazy Loading & Route Guards"
                        },
                        new
                        {
                            Id = 15,
                            SkillCategoryId = 2,
                            TopicName = "Interceptors (Auth, Error Handling)"
                        },
                        new
                        {
                            Id = 16,
                            SkillCategoryId = 2,
                            TopicName = "State Management Libraries (NgRx)"
                        },
                        new
                        {
                            Id = 17,
                            SkillCategoryId = 2,
                            TopicName = "Performance Optimization (Bundle Size reduction)"
                        },
                        new
                        {
                            Id = 18,
                            SkillCategoryId = 2,
                            TopicName = "Custom Directives & Pipes"
                        },
                        new
                        {
                            Id = 19,
                            SkillCategoryId = 2,
                            TopicName = "SSR (Server-Side Rendering) & Hydration"
                        },
                        new
                        {
                            Id = 20,
                            SkillCategoryId = 2,
                            TopicName = "WebSockets & SignalR Integration"
                        },
                        new
                        {
                            Id = 21,
                            SkillCategoryId = 3,
                            TopicName = "Query Execution Plans & Optimization"
                        },
                        new
                        {
                            Id = 22,
                            SkillCategoryId = 3,
                            TopicName = "Indexing Strategies (Clustered vs. Non-Clustered)"
                        },
                        new
                        {
                            Id = 23,
                            SkillCategoryId = 3,
                            TopicName = "N+1 Problem & Eager/Lazy Loading"
                        },
                        new
                        {
                            Id = 24,
                            SkillCategoryId = 3,
                            TopicName = "Dapper for High-Performance Read Paths"
                        },
                        new
                        {
                            Id = 25,
                            SkillCategoryId = 3,
                            TopicName = "Database Migrations & CI/CD Versioning"
                        },
                        new
                        {
                            Id = 26,
                            SkillCategoryId = 3,
                            TopicName = "Transactions & Isolation Levels (Deadlocks)"
                        },
                        new
                        {
                            Id = 27,
                            SkillCategoryId = 3,
                            TopicName = "Connection Pooling"
                        },
                        new
                        {
                            Id = 28,
                            SkillCategoryId = 3,
                            TopicName = "Stored Procedures vs. ORM"
                        },
                        new
                        {
                            Id = 29,
                            SkillCategoryId = 3,
                            TopicName = "Data Modeling & Normalization"
                        },
                        new
                        {
                            Id = 30,
                            SkillCategoryId = 3,
                            TopicName = "Partitioning & Archiving Strategies"
                        },
                        new
                        {
                            Id = 31,
                            SkillCategoryId = 4,
                            TopicName = "CI/CD Pipelines (YAML in Azure DevOps/GitHub Actions)"
                        },
                        new
                        {
                            Id = 32,
                            SkillCategoryId = 4,
                            TopicName = "Infrastructure as Code (Bicep/Terraform)"
                        },
                        new
                        {
                            Id = 33,
                            SkillCategoryId = 4,
                            TopicName = "Docker Containerization"
                        },
                        new
                        {
                            Id = 34,
                            SkillCategoryId = 4,
                            TopicName = "Azure App Services & Serverless (Functions)"
                        },
                        new
                        {
                            Id = 35,
                            SkillCategoryId = 4,
                            TopicName = "Secrets Management (Azure Key Vault)"
                        },
                        new
                        {
                            Id = 36,
                            SkillCategoryId = 4,
                            TopicName = "Blue/Green & Canary Deployments"
                        },
                        new
                        {
                            Id = 37,
                            SkillCategoryId = 4,
                            TopicName = "Role-Based Access Control (RBAC) & Managed Identities"
                        },
                        new
                        {
                            Id = 38,
                            SkillCategoryId = 4,
                            TopicName = "Load Balancing & Traffic Manager"
                        },
                        new
                        {
                            Id = 39,
                            SkillCategoryId = 4,
                            TopicName = "Container Orchestration (Azure Container Apps)"
                        },
                        new
                        {
                            Id = 40,
                            SkillCategoryId = 4,
                            TopicName = "API Management (APIM)"
                        },
                        new
                        {
                            Id = 41,
                            SkillCategoryId = 5,
                            TopicName = "Domain-Driven Design (DDD - Entities, Aggregates)"
                        },
                        new
                        {
                            Id = 42,
                            SkillCategoryId = 5,
                            TopicName = "Microservices vs. Modular Monolith"
                        },
                        new
                        {
                            Id = 43,
                            SkillCategoryId = 5,
                            TopicName = "CQRS (Command Query Responsibility Segregation)"
                        },
                        new
                        {
                            Id = 44,
                            SkillCategoryId = 5,
                            TopicName = "Event-Driven Architecture (Pub/Sub)"
                        },
                        new
                        {
                            Id = 45,
                            SkillCategoryId = 5,
                            TopicName = "Message Brokers (Azure Service Bus, RabbitMQ)"
                        },
                        new
                        {
                            Id = 46,
                            SkillCategoryId = 5,
                            TopicName = "API Gateway Pattern"
                        },
                        new
                        {
                            Id = 47,
                            SkillCategoryId = 5,
                            TopicName = "Distributed Caching (Redis)"
                        },
                        new
                        {
                            Id = 48,
                            SkillCategoryId = 5,
                            TopicName = "Rate Limiting & Throttling"
                        },
                        new
                        {
                            Id = 49,
                            SkillCategoryId = 5,
                            TopicName = "SAGA Pattern & Distributed Transactions"
                        },
                        new
                        {
                            Id = 50,
                            SkillCategoryId = 5,
                            TopicName = "CAP Theorem & Database Selection"
                        },
                        new
                        {
                            Id = 51,
                            SkillCategoryId = 6,
                            TopicName = "Test-Driven Development (TDD: Red-Green-Refactor)"
                        },
                        new
                        {
                            Id = 52,
                            SkillCategoryId = 6,
                            TopicName = "Unit Testing (xUnit)"
                        },
                        new
                        {
                            Id = 53,
                            SkillCategoryId = 6,
                            TopicName = "Mocking Frameworks (Moq, NSubstitute)"
                        },
                        new
                        {
                            Id = 54,
                            SkillCategoryId = 6,
                            TopicName = "Integration Testing (WebApplicationFactory, Testcontainers)"
                        },
                        new
                        {
                            Id = 55,
                            SkillCategoryId = 6,
                            TopicName = "Structured Logging (Serilog)"
                        },
                        new
                        {
                            Id = 56,
                            SkillCategoryId = 6,
                            TopicName = "Distributed Tracing (OpenTelemetry)"
                        },
                        new
                        {
                            Id = 57,
                            SkillCategoryId = 6,
                            TopicName = "Metrics & Dashboards (Application Insights/Grafana)"
                        },
                        new
                        {
                            Id = 58,
                            SkillCategoryId = 6,
                            TopicName = "Application Health Checks"
                        },
                        new
                        {
                            Id = 59,
                            SkillCategoryId = 6,
                            TopicName = "Alerting & Incident Response"
                        },
                        new
                        {
                            Id = 60,
                            SkillCategoryId = 6,
                            TopicName = "Load Testing (k6, JMeter)"
                        });
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.SkillCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DevHexagonId")
                        .HasColumnType("int");

                    b.Property<string>("HighLevelGoal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InterviewGotcha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DevHexagonId");

                    b.ToTable("SkillCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Backend (.NET)",
                            DevHexagonId = 1,
                            HighLevelGoal = "Reliability & Performance",
                            InterviewGotcha = "How do you handle a failing 3rd party API?"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Frontend (Angular)",
                            DevHexagonId = 1,
                            HighLevelGoal = "User Experience & State Management",
                            InterviewGotcha = "How do you optimize a page with 1,000+ data rows?"
                        },
                        new
                        {
                            Id = 3,
                            Category = "DBMS (SQL Server & EF Core)",
                            DevHexagonId = 1,
                            HighLevelGoal = "Data Integrity & Query Optimization",
                            InterviewGotcha = "Explain your strategy for database migrations in production."
                        },
                        new
                        {
                            Id = 4,
                            Category = "DevOps (Azure)",
                            DevHexagonId = 1,
                            HighLevelGoal = "Automation & CI/CD",
                            InterviewGotcha = "How do you ensure zero-downtime deployments?"
                        },
                        new
                        {
                            Id = 5,
                            Category = "System Design & Architecture",
                            DevHexagonId = 1,
                            HighLevelGoal = "Scalability & Resilience",
                            InterviewGotcha = "How would you handle a 10x spike in traffic?"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Testing & Observability",
                            DevHexagonId = 1,
                            HighLevelGoal = "Maintainability & Fast Debugging",
                            InterviewGotcha = "How do you identify a memory leak in a production environment?"
                        });
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.StudyGuideSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("StudyGuideSections");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.UserProgress", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRevision")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSolved")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Category", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.CheatSheetResource", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.PrimaryMetric", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.DevHexagon", "DevHexagon")
                        .WithMany("PrimaryMetrics")
                        .HasForeignKey("DevHexagonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevHexagon");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Question", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuestionVersion", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Question", "Question")
                        .WithMany("Versions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuizAttempt", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuizAttemptQuestion", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.QuizAttempt", "QuizAttempt")
                        .WithMany("Questions")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewPrepApp.Domain.Entities.QuizQuestion", "QuizQuestion")
                        .WithMany()
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuizAttempt");

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuizAttemptResponse", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.QuizAttemptQuestion", "QuizAttemptQuestion")
                        .WithOne("Response")
                        .HasForeignKey("InterviewPrepApp.Domain.Entities.QuizAttemptResponse", "QuizAttemptQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizAttemptQuestion");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuizQuestion", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Skill", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.SkillCategory", "SkillCategory")
                        .WithMany("KeyTopics")
                        .HasForeignKey("SkillCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillCategory");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.SkillCategory", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.DevHexagon", "DevHexagon")
                        .WithMany("Skills")
                        .HasForeignKey("DevHexagonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevHexagon");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.StudyGuideSection", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.UserProgress", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.Question", "Question")
                        .WithMany("UserProgresses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InterviewPrepApp.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Category", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.DevHexagon", b =>
                {
                    b.Navigation("PrimaryMetrics");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.Question", b =>
                {
                    b.Navigation("UserProgresses");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuizAttempt", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.QuizAttemptQuestion", b =>
                {
                    b.Navigation("Response");
                });

            modelBuilder.Entity("InterviewPrepApp.Domain.Entities.SkillCategory", b =>
                {
                    b.Navigation("KeyTopics");
                });
#pragma warning restore 612, 618
        }
    }
}
